### ISSUE TITLE
Unable to run tests on Windows

### ISSUE THREAD

**Issue by nathan-osman** [giddie/qt-cmake-template#2]
I attempted to build and test the project on Windows Server 2012 with Visual Studio 2013 Express installed, but ran into a small problem.

I renamed `tests/example_tests.cpp.example` to `tests/example_tests.cpp` and then attempted to run `ctest` in the project binary directory. This produced the following error:

![](http://i.stack.imgur.com/NtmUx.png)

Steps taken:
1. opened a command window and run `vcvarsall.bat` to set the appropriate environment variables for building with the x86 compiler and pointed CMake to the Qt modules:
   
   ```
   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat x86
   set CMAKE_PREFIX_PATH=C:\Qt\5.4\msvc2013_opengl\lib\cmake
   ```
2. created a directory for the binary files
   
   ```
   mkdir build
   cd build
   ```
3. configured and built the project
   
   ```
   cmake -G "NMake Makefiles" ..
   nmake
   ```
4. attempted to run the tests:
   
   ```
   ctest
   ```

**Comment by giddie** [comment]
This is probably happening because the Qt DLLs are not in your PATH. Make sure that the PATH environment variable includes the directory that Qt5Test.dll is in.

I recommend grabbing a copy of "Dependency Walker" (http://dependencywalker.com/). If you open an executable with that tool, it'll give you a good indication of which DLLs are required by that executable, and which ones it's going to use (if they've been found).
